services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pw
      TZ: Europe/Spain
    secrets:
      - pg_user
      - pg_pw
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
      - ./certs:/var/lib/postgresql/certs
    ports:
      - "5432:5432"
    command: >
      postgres -c ssl=on
               -c ssl_cert_file=/var/lib/postgresql/certs/server.crt
               -c ssl_key_file=/var/lib/postgresql/certs/server.key
               -c logging_collector=on
               -c log_directory=/var/log/postgresql
               -c log_filename=postgresql.log
               -c log_statement=all
               -c log_connections=on
               -c log_disconnections=on
               -c log_destination=stderr,csvlog
               -c log_rotation_age=1d
               -c shared_preload_libraries=pg_stat_statements
               -c pg_stat_statements.track=all
    restart: unless-stopped

secrets:
  pg_user:
    file: ./secrets/pg_user.txt
  pg_pw:
    file: secrets/pg_pw.txt